import Groq from "groq-sdk";

const ai = new Groq({ apiKey: import.meta.env.VITE_GROQ_API_KEY, dangerouslyAllowBrowser: true });
const MODEL = "llama-3.3-70b-versatile";

export interface RefineOptions {
  processingMode: string;
  context: string;
  developerMode: boolean;
  editingControls: {
    removeEmDashes: boolean;
    grammarCorrection: boolean;
    clarityConciseness: boolean;
    structuralRefinement: boolean;
    toneAlignment: boolean;
  };
  aiPreset: string;
  structureGenerator: boolean;
  optimizationPass: boolean;
}

export async function refineText(text: string, options: RefineOptions): Promise<string> {
  const {
    processingMode,
    context,
    developerMode,
    editingControls,
    aiPreset,
    structureGenerator,
    optimizationPass,
  } = options;

  let prompt = "";

  if (processingMode === "Remove Em Dashes Only") {
    prompt = `You are an expert editor. Your ONLY task is to remove all em dashes (—) from the following text and replace them with contextually correct punctuation such as commas, periods, semicolons, or parentheses. Do NOT change any other words, grammar, or formatting.\n\nHere is the raw text:\n<raw_text>\n${text}\n</raw_text>\n\nProvide ONLY the modified text in your response, without any conversational filler.`;
  } else if (processingMode === "Grammar Correction Only") {
    prompt = `You are an expert editor. Your ONLY task is to correct any grammar, spelling, and language errors in the following text. Do NOT rewrite the text for tone, style, or structure unless it is grammatically incorrect. Preserve the original meaning, voice, and formatting.\n\nHere is the raw text:\n<raw_text>\n${text}\n</raw_text>\n\nProvide ONLY the corrected text in your response, without any conversational filler.`;
  } else if (processingMode === "De-AI / Humanize Text") {
    prompt = `You are an expert human editor. Your task is to "de-AI" or "humanize" the following text, which was likely generated by an LLM.

Please apply the following strict rules:
- Convert all American English spelling and phrasing to British English (e.g., "color" to "colour", "optimize" to "optimise").
- Remove all em dashes (—) and replace them with contextually correct punctuation (commas, periods, semicolons, or parentheses).
- Eliminate common AI buzzwords, clichés, and overly flowery language (e.g., "delve", "tapestry", "testament", "beacon", "navigate the landscape", "fostering", "seamless", "robust", "crucial").
- Remove robotic transitions and filler (e.g., "Furthermore", "In conclusion", "It is important to note").
- Vary sentence lengths and structures to sound more like natural human writing.
- Ensure the tone is authentic, direct, and professional without being dramatic or exaggerated.

Here is the raw text:\n<raw_text>\n${text}\n</raw_text>\n\nProvide ONLY the humanized text in your response, without any conversational filler.`;
  } else {
    prompt = `You are an expert editor and technical writer. Your task is to refine the following rough text.\n\n`;

    if (developerMode) {
      prompt += `The user wants to transform this text into a structured prompt for an AI coding agent.\n`;
    } else {
      prompt += `The target writing context is: ${context}. Adjust tone, structure, and vocabulary appropriately.\n`;
    }

    prompt += `\nPlease apply the following editing rules:\n`;
    if (editingControls.removeEmDashes) {
      prompt += `- Remove em dashes (—) and replace them with contextually correct punctuation such as commas, periods, semicolons, or parentheses.\n`;
    }
    if (editingControls.grammarCorrection) {
      prompt += `- Correct any grammar, spelling, and language errors.\n`;
    }
    if (editingControls.clarityConciseness) {
      prompt += `- Improve clarity and conciseness. Remove fluff.\n`;
    }
    if (editingControls.structuralRefinement) {
      prompt += `- Refine the structure, improving paragraph flow and sentence clarity.\n`;
    }
    if (editingControls.toneAlignment && !developerMode) {
      prompt += `- Align the tone perfectly with the selected writing context (${context}).\n`;
    }

    if (developerMode) {
      if (structureGenerator) {
        prompt += `\nSince this is a Developer Prompt, reorganize the output into the following explicit sections:\n`;
        prompt += `- Goal\n- Requirements\n- Constraints\n- Tech stack\n- Expected output\n`;
      }
      if (aiPreset !== "None") {
        prompt += `\nFormat the output to match the style commonly used for a ${aiPreset} prompt, ensuring it is immediately usable.\n`;
      }
    }

    prompt += `\nHere is the raw text to refine:\n<raw_text>\n${text}\n</raw_text>\n\nProvide ONLY the refined text in your response, without any conversational filler.`;
  }

  try {
    const response = await ai.chat.completions.create({
      model: MODEL,
      messages: [{ role: "user", content: prompt }],
    });

    let refinedText = response.choices[0]?.message?.content || "";

    // Optional second pass
    if (developerMode && optimizationPass) {
      const optPrompt = `You are an expert AI prompt engineer. Review the following prompt intended for an AI coding agent and optimize it.
Your goals:
- Remove any remaining ambiguity or vague language.
- Tighten instructions to be highly actionable.
- Ensure all requirements are explicit.
- Produce cleaner step-based instructions when appropriate.
- Improve overall compatibility with AI coding tools.

Here is the prompt to optimize:
<prompt>
${refinedText}
</prompt>

Provide ONLY the optimized prompt in your response, without any conversational filler.`;

      const optResponse = await ai.chat.completions.create({
        model: MODEL,
        messages: [{ role: "user", content: optPrompt }],
      });

      refinedText = optResponse.choices[0]?.message?.content || refinedText;
    }

    return refinedText;
  } catch (error: any) {
    console.error("Error refining text:", error);
    if (error?.status === 429 || error?.message?.includes("429") || error?.message?.includes("rate_limit") || error?.message?.includes("quota")) {
      throw new Error("You have exceeded your Groq API rate limit. Please wait a moment and try again.");
    }
    throw new Error("Failed to refine text. Please try again.");
  }
}
